name: equ_layer
channels:
  - conda-forge
dependencies:
  - python=3.12
  - anyio=4.6.2.post1
  - apiclient=1.0.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astropy=6.1.4
  - astropy-iers-data=0.2024.10.28.0.34.7
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.16.0
  - basemap=1.4.1
  - basemap-data=1.3.2
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - cartopy=0.24.1
  - certifi=2024.8.30
  - cffi=1.17.1
  - cftime=1.6.4.post1
  - charset-normalizer=3.4.0
  - cmcrameri=1.9
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - debugpy=1.8.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=2.1.0
  - fastjsonschema=2.20.0
  - fonttools=4.54.1
  - fqdn=1.5.1
  - geopandas=1.0.1
  - h11=0.14.0
  - hapiclient=0.2.6
  - httpcore=1.0.6
  - httpx=0.27.2
  - idna=3.10
  - ipykernel=6.29.5
  - ipython=8.29.0
  - isodate=0.7.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter-client=8.6.3
  - jupyter-core=5.7.2
  - jupyter-events=0.10.0
  - jupyter-lsp=2.2.5
  - jupyter-server=2.14.2
  - jupyter-server-terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab-pygments=0.3.0
  - jupyterlab-server=2.27.3
  - kiwisolver=1.4.7
  - llvmlite=0.43.0
  - markupsafe=3.0.2
  - matplotlib=3.8.4
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mpl-tools=0.4.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - notebook-shim=0.2.4
  - numba=0.60.0
  - numpy=1.26.4
  - overrides=7.7.0
  - packaging=23.2
  - pandas=2.2.3
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pillow=11.0.0
  - platformdirs=4.3.6
  - pooch=1.8.2
  - prometheus-client=0.21.0
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pure-eval=0.2.3
  - pycparser=2.22
  - pyerfa=2.0.1.4
  - pygments=2.18.0
  - pyogrio=0.10.0
  - pyparsing=3.2.0
  - pyproj=3.6.1
  - pyshp=2.3.1
  - pyshtools=4.13.1
  - python-dateutil=2.9.0.post0
  - python-json-logger=2.0.7
  - pytz=2024.2
  - pywavelets=1.7.0
  - pywin32=308
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - scipy=1.14.1
  - send2trash=1.8.3
  - shapely=2.0.6
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.6
  - stack-data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tornado=6.4.1
  - tqdm=4.66.6
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - tzdata=2024.2
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - xarray=2024.10.0
